name = "Whisper"
license = "MIT"
licenselink = "https://github.com/JugglerX/hugo-whisper-theme/blob/master/LICENSE"
description = "Ivan built this documentation theme with Hugo. The design and functionality is intentionally minimal."
homepage = "https://github.com/jugglerx/hugo-whisper-theme"
tags = ["documentation","responsive","minimal","clean","bootstrap","zerostatic"]
features = ["docs"]
min_version = 0.51

[author]
  name = "Ivan Cheban"
  homepage = "https://ivanchebancv.netlify.app/"